# Ruby Windows pipeline

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:



- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
  displayName: 'Restore Packages'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
  displayName: 'Build Project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'Run Unit Tests'
